const fetch = require('node-fetch')
const {default: mix} = require('@es-git/mix')
const {default: FsRepo} = require('@es-git/node-fs-repo')
const {default: MemRepo} = require('@es-git/memory-repo')
const {default: zlibMixin} = require('@es-git/zlib-mixin')
const {default: fetchMixin} = require('@es-git/fetch-mixin')
const {default: objectMixin} = require('@es-git/object-mixin')
const {default: loadAsMixin} = require('@es-git/load-as-mixin')
const {default: saveAsMixin} = require('@es-git/save-as-mixin')
const {default: walkersMixin} = require('@es-git/walkers-mixin')
const {default: checkoutMixin} = require('@es-git/checkout-mixin')
const {default: commitMixin} = require('@es-git/commit-mixin')
const {default: pathToObjectMixin} = require('@es-git/path-to-object-mixin')
const entriesMixin = require('./entry-mixin')

exports.FsRepo = mix(FsRepo)
.with(zlibMixin)
.with(fetchMixin, fetch)
.with(objectMixin)
.with(loadAsMixin)
.with(saveAsMixin)
.with(walkersMixin)
.with(checkoutMixin)
.with(commitMixin)
.with(pathToObjectMixin)
.with(entriesMixin)

exports.MemRepo = mix(MemRepo)
.with(fetchMixin, fetch)
.with(objectMixin)
.with(loadAsMixin)
.with(saveAsMixin)
.with(walkersMixin)
.with(checkoutMixin)
.with(commitMixin)
.with(pathToObjectMixin)
.with(entriesMixin)
